language: python
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
script:
  - docker build . -t ghetyman/website
  - bash docker_push
  - bash deploy.sh