version: '3'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: alex
      MONGO_INITDB_ROOT_PASSWORD: VQeUuc9NmneULQEGdPcEckhg
      MONGO_INITDB_DATABASE: projects
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  web:
    build: .
    ports:
      - "8080:5000"
    links:
      - "mongo:database"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    links:
      - "web:flask"
    ports:
      - 80:80
      - 443:443
networks:
    my-network:
      aliases:
        - flask-app