version: '3'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: alex
      MONGO_INITDB_ROOT_PASSWORD: VQeUuc9NmneULQEGdPcEckhg
      MONGO_INITDB_DATABASE: projects
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - docker-network
  web:
    build: .
    ports:
      - "443"
    #  - "8081:5001"
    links:
      - "mongo:database"
    networks:
      - docker-network
  nginx:
    image: nginx:latest
    depends_on:
      - web
    links:
      - "web:flask"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log/error.log
      - ./nginx/cache:/etc/nginx/cache
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - docker-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  docker-network:
